### PR TITLE
Add Files

### PR DESCRIPTION
**Pull request by EnderInvader**
Add pt.ts and pt.ts.meta, uuid left blank, language changed to portuguese and abbreviation changed to pt.

### CODE REVIEW

**Comment by insraq** [comment]
Is there a reason to distinguish between PT and PT_BR? Also assume the file is gonna be translated at some point? (the PR shows it's just a copy of English). You can leave the meta file out - the engine will generate those.

**Comment by EnderInvader** [comment]
@Lelozitos#3139 in discord was asking for a file for portuguese translation, personally I don't know the different between PT and PT_BR, but he seemed to distinguish between the two.

**Comment by Lelozitos** [comment]
There more differences between PT and PT_BR than the English from UK and the US. The main difference is that in PT_BR we don't use the second person. We can understand each other but it is more of a life quality change.

**Comment by insraq** [comment]
@Lelozitos It's here: https://github.com/fishpondstudio/IndustryIdle-i18n/blob/main/pt-BR.ts

**Pull request closed without merging**
